// This runner is auto-generated by Brittle

await runTests()

async function runTests() {
  const test = (await import('brittle')).default

  test.pause()

  await test.load(import.meta.resolve('./paths.js'))
  await test.load(import.meta.resolve('./no-conditional-spread.js'))
  await test.load(import.meta.resolve('./no-catch-fabricate.js'))
  await test.load(import.meta.resolve('./prefer-for-await.js'))

  test.resume()
}
