// This runner is auto-generated by Brittle

await runTests()

async function runTests() {
  const test = (await import('brittle')).default

  test.pause()

  await test.load(import.meta.resolve('./paths.js'))
  await test.load(import.meta.resolve('./no-conditional-spread.js'))
  await test.load(import.meta.resolve('./no-catch-fabricate.js'))
  await test.load(import.meta.resolve('./prefer-for-await.js'))
  await test.load(import.meta.resolve('./no-sleep.js'))
  await test.load(import.meta.resolve('./no-settimeout.js'))
  await test.load(import.meta.resolve('./no-buffer-global.js'))
  await test.load(import.meta.resolve('./no-explicit-any.js'))
  await test.load(import.meta.resolve('./no-as-cast.js'))
  await test.load(import.meta.resolve('./no-init-method.js'))
  await test.load(import.meta.resolve('./no-utils-file.js'))

  test.resume()
}
